//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagazaUrunTakipSistemi.Models.Entity
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel.DataAnnotations;

	public partial class TblMusteri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblMusteri()
        {
            this.TblSatis = new HashSet<TblSatis>();
        }
    
        public int Id { get; set; }
		[Required(ErrorMessage ="Müþteri Adýný Girmelisiniz")]
        public string Ad { get; set; }
		[Required(ErrorMessage = "Müþteri Soyadýný Girmelisiniz")]
		public string Soyad { get; set; }
		[Required(ErrorMessage = "Þehir Alanýný Girmelisiniz")]
		public string Sehir { get; set; }
        public Nullable<decimal> Bakiye { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblSatis> TblSatis { get; set; }
    }
}
